# -*- coding: utf-8 -*-
"""Exp11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z81AdNsMDMCSsgo4tU051GtOgV_Kury9
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
df=pd.read_csv("/movies.csv")
#preprocessing step
df["genres"]=df["genres"].fillna("")
df["overview"]=df["overview"].fillna("")
df["content"]=df["genres"]+" "+df['overview']
#TF-IDF Vectorizer
tfidf=TfidfVectorizer(stop_words="english")
tfidf_matrix=tfidf.fit_transform(df["content"])
cosine_sim=cosine_similarity(tfidf_matrix,tfidf_matrix)
#droping the duplicates
indices=pd.Series(df.index,index=df["original_title"]).drop_duplicates()
def recommendation_movie(title,topn=5):
  if title not in indices:
    return "Movie is not found!"
  idx=indices[title]
  sim_scores=list(enumerate(cosine_sim[idx]))
  sim_scores=sorted(sim_scores,key=lambda x:x[1],reverse=True)
  sim_scores=sim_scores[1:topn+1]
  movie_indices=[i[0] for i in sim_scores]
  return df["original_title"].iloc[movie_indices]
recommendation_movie("Inception")