# -*- coding: utf-8 -*-
"""ex7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FdC1z2RVyHa7aOgzvGfryagVrWepg2G_
"""

from collections import Counter

def generate_ngrams(text, n):
    # Tokenize text into words
    words = text.lower().split()

    # Generate n-grams
    ngrams = zip(*[words[i:] for i in range(n)])
    ngrams_list = [" ".join(ngram) for ngram in ngrams]

    return ngrams_list

# Example text (you can replace with your portfolio or any document)
text = "Machine learning is widely used in applications such as recommendation systems, fraud
detection, and image recognition."

# Generate dynamic N-Grams
for n in range(1, 4):  # Unigrams, Bigrams, Trigrams
    ngrams = generate_ngrams(text, n)
    freq = Counter(ngrams)
    print(f"\nTop {n}-grams:")
    for gram, count in freq.most_common(5):
        print(f"{gram} -> {count}")