# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S_CBoZY68hWhND4Ys9LH1IZUX--fYIgc
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

def process_image(img):
    """Process image and count microplastic particles"""

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


    blur = cv2.GaussianBlur(gray, (7, 7), 0)

    _, thresh = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)


    kernel = np.ones((3, 3), np.uint8)
    clean = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel, iterations=2)


    contours, _ = cv2.findContours(clean, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    count = 0
    output = img.copy()

    for c in contours:
        area = cv2.contourArea(c)
        if area > 20:
            x, y, w, h = cv2.boundingRect(c)
            cv2.rectangle(output, (x, y), (x+w, y+h), (0,255,0), 2)
            count += 1

    return output, count


print("📤 Upload microscope images now:")
uploaded = files.upload()

for file_name in uploaded.keys():
    print(f"\nProcessing: {file_name}")


    img = cv2.imdecode(np.frombuffer(uploaded[file_name], np.uint8), cv2.IMREAD_COLOR)

    result, count = process_image(img)

    print(f"🟦 Microplastic particles detected: {count}")

    plt.figure(figsize=(8, 8))
    plt.title(f"Detected particles: {count}")
    plt.imshow(cv2.cvtColor(result, cv2.COLOR_BGR2RGB))
    plt.axis("off")
    plt.show()