# -*- coding: utf-8 -*-
"""exp8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wt1QoGhQ65mzDWRkzaMKkpd4pH4iOn8_
"""

import spacy
nlp = spacy.load('en_core_web_sm')

#POS Tags: Part of speech taggings
#text="Google is a very good search engine"
text="Let's google it"
doc=nlp(text)
for token in doc:
  print(token.text, token.pos_)

#Lemmatization vs stemming
text="""I studied the subject AI and then
meeting Mr. Sachin tommorrow in the meeting"""

import nltk
from nltk.stem.porter import *  ## stemming
p_stem=PorterStemmer()
for word in text.split():
  print(word,"-->", p_stem.stem(word))

#lemmatization
for token in nlp(text):
  print(token.text,"- ",token.pos_,
        "- ",token.lemma_)

#punctuation marks
import string
string.punctuation

#stopwords
from nltk.corpus import stopwords
nltk.download('stopwords')
print(set(stopwords.words('english')))